services:
  postgres:
    image: postgres:16-alpine
    container_name: eru-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-eru}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-change-me}
    ports:
      - "5432:5432"
    volumes:
      - eru-postgres-data:/var/lib/postgresql/data

volumes:
  eru-postgres-data:
