### Register user
POST {{url}}/auth/register
Content-Type: application/json

{
  "firstName": "Student",
  "lastName": "One",
  "email": "student1@example.com",
  "username": "student1",
  "password": "secret123"
}

###
### Login user
POST {{url}}/auth/login
Content-Type: application/json

{
  "username": "student1",
  "password": "secret123"
}

> {% client.global.set("token", response.body.token); %}

###
### Current authenticated user
GET {{url}}/auth/me
Authorization: Bearer {{token}}

###
### Logout user
POST {{url}}/auth/logout
Authorization: Bearer {{token}}

> {% client.global.clear("token"); %}

###
### Promote user to ADMIN
POST {{url}}/auth/roles
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "student1",
  "role": "ADMIN"
}
